from ccprojects.models import ImpactType
ImpactType.objects.create(impact_type="Finance",type_required="Change").save()
ImpactType.objects.create(impact_type="Generic",type_required="Project").save()
ImpactType.objects.create(impact_type="Human Resources",type_required="Change").save()
ImpactType.objects.create(impact_type="Marketing",type_required="Change").save()
ImpactType.objects.create(impact_type="Training",type_required="Change").save()
ImpactType.objects.create(impact_type="Distribution",type_required="Change").save()
ImpactType.objects.create(impact_type="Freelance",type_required="Change").save()
ImpactType.objects.create(impact_type="Capital Change",type_required="Change").save()
ImpactType.objects.create(impact_type="Compliance Government",type_required="Change").save()
ImpactType.objects.create(impact_type="Compliance Association",type_required="Change").save()
ImpactType.objects.create(impact_type="Compliance Self",type_required="Change").save()
ImpactType.objects.create(impact_type="Customer",type_required="Change").save()
ImpactType.objects.create(impact_type="Critical",type_required="Change").save()
ImpactType.objects.create(impact_type="Reputation Risk",type_required="Change").save()
ImpactType.objects.create(impact_type="Reputation",type_required="Change").save()
ImpactType.objects.create(impact_type="Reputation",type_required="Project").save()
ImpactType.objects.create(impact_type="Reputation Risk",type_required="Project").save()
ImpactType.objects.create(impact_type="Compliance",type_required="Project").save()
ImpactType.objects.create(impact_type="Compliance Change",type_required="Project").save()
ImpactType.objects.create(impact_type="Compliance Revised",type_required="Project").save()
ImpactType.objects.create(impact_type="Compliance Remediate",type_required="Project").save()
ImpactType.objects.create(impact_type="Disaster Recovery",type_required="Project").save()
ImpactType.objects.create(impact_type="Disaster Mitigation",type_required="Project").save()
ImpactType.objects.create(impact_type="Costing",type_required="Project").save()
ImpactType.objects.create(impact_type="Existing Project",type_required="Project").save()
ImpactType.objects.create(impact_type="Decommission",type_required="Project").save()
ImpactType.objects.create(impact_type="Project Backout",type_required="Project").save()
